// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenderScraper.Infrastructure;

#nullable disable

namespace TenderScraper.Migrations
{
    [DbContext(typeof(TenderDbContext))]
    partial class TenderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenderScraper.Infrastructure.Tender", b =>
                {
                    b.Property<int>("TenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenderID"));

                    b.Property<string>("BuyerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EligibilityProbability")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("EnglishExecutiveSummary")
                        .HasColumnType("text");

                    b.Property<string>("FatalFlaws")
                        .HasColumnType("text");

                    b.Property<string>("HardCertifications")
                        .HasColumnType("text");

                    b.Property<string>("RawXml")
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SuitabilityScore")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<string>("TechStack")
                        .HasColumnType("text");

                    b.Property<string>("TitleDe")
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueEuro")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("TenderID");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Tenders");
                });
#pragma warning restore 612, 618
        }
    }
}
